### PR TITLE
Ahnai17

### PR DESCRIPTION
**Pull request by Samirez**

### CODE REVIEW

**Comment by mjako18** [comment]
Have a look at your database tables .txt file, there are some text that shouldnt be there.
Your CreateUser .php doesnt really make sense. You shouldnt use $username and $password in the prepare but username and password, which is the 1st parameter you use in the 2 bindParam.
In the bindParam for password you should probably use $password_hash and not $password, since $password is plaintext.
I am not sure why you have that if statement in there, surely it will always evaluate to false?
if you want to check if the user was created maybe check on the execute() method on php.net(https://www.php.net/manual/en/pdostatement.execute.php) and perhaps rowCount(https://www.php.net/manual/en/pdostatement.rowcount.php)?
You might want to consider making the database connection into a function that returns the connection and put it in db_config .php, only comment I have for that file.
upload .php looks ok, though you might want to write the error text for filesize a little differently.
LoginPage .html:
this shouldnt be in the &lt;head&gt; section:
&lt;div class="header"&gt;&lt;h1&gt;Welcome to website for image gallery&lt;/h1&gt;&lt;/div&gt;
all those &nbsp you have after &lt;br&gt; is a waste.
Maybe have some indication that you can click on the link for create new user. ie it shouldnt look like ordinary text.
Register_new_user .html:
this shouldnt be in the &lt;head&gt; section:
&lt;div class="userhead"&gt;&lt;h1&gt;Registration form&lt;/h1&gt;&lt;/div&gt;
redo the layout for the form, never use &lt;table&gt; for that!!
The go back link, might not be a good idea, that functionality is part of the browser already.
web_gallery .html:
simple, needs a little attention with the design. The name of the file is a bit odd, as I would have thought that web_gallery .html would be the file that showed all the images, not the 1 used to upload files.
js:
I wouldnt put an upper limit on the password.
you might want to consider adding some code that tells the user if a password or username doesnt work and why on the actual website, not just in the console. normal users dont have that open ever
CSS:
Just skimmed it, but I'll just remind you that you can use the same classes on all your pages, no need to redo the same things with different names(container/wrapper) and maybe pick some less intrusive colours.

**Comment by Samirez** [comment]
I have corrected upon your feedback thank you but now i have trouble showings users by calling both javascript ajax call and php file SearchUsers so if you have time it would kind of you spent 5 minutes on seeing what is wrong, because it doesnt display any username when I use the search bar

________________________________
Fra: Mathias Jakobsen <notifications@github.com>
Sendt: 28. februar 2020 09:24:54
Til: LangeHenrik/SDU-ITI-F20
Cc: Ahmadullah Naibi; Author
Emne: Re: [LangeHenrik/SDU-ITI-F20] Ahnai17 (#5)


Have a look at your database tables.txt file, there are some text that shouldnt be there.
Your CreateUser.php doesnt really make sense. You shouldnt use $username and $password in the prepare but username and password, which is the 1st parameter you use in the 2 bindParam.
In the bindParam for password you should probably use $password_hash and not $password, since $password is plaintext.
I am not sure why you have that if statement in there, surely it will always evaluate to false?
if you want to check if the user was created maybe check on the execute() method on php.net(https://www.php.net/manual/en/pdostatement.execute.php) and perhaps rowCount(https://www.php.net/manual/en/pdostatement.rowcount.php)?
You might want to consider making the database connection into a function that returns the connection and put it in db_config.php, only comment I have for that file.
upload.php looks ok, though you might want to write the error text for filesize a little differently.
LoginPage.html:
this shouldnt be in the section:

Welcome to website for image gallery
all those   you have after
is a waste. Maybe have some indication that you can click on the link for create new user. ie it shouldnt look like ordinary text. Register_new_user.html: this shouldnt be in the section:
Registration form
redo the layout for the form, never use for that!! The go back link, might not be a good idea, that functionality is part of the browser already. web_gallery.html: simple, needs a little attention with the design. the name of the file is a bit odd, as I would have thought that web_gallery.html would be the file that showed all the images, not the 1 used to upload files. js: I wouldnt put an upper limit on the password. you might want to consider adding some code that tells the user if a password or username doesnt work and why on the actual website, not just in the console. normal users dont have that open ever CSS: Just skimmed it, but I'll just remind you that you can use the same classes on all your pages, no need to redo the same things with different names(container/wrapper) and maybe pick some less intrusive colours.

**Comment by mjako18** [comment]
In searchuser.js you have displayuser.php?q= and in displayuser.php you have ['search_username']
Thats why it wont work. the text between ? and = in the js file should be what you look for in the filter_input in php file
That said, I would probably use POST for an ajax call and not GET.

**Comment by Samirez** [comment]
I have changed the name and Id to match but it still doesn’t show anything on the home page

On 8 Mar 2020, at 09.36, Mathias Jakobsen <notifications@github.com> wrote:

﻿

In searchuser.js you have displayuser.php?q= and in displayuser.php you have ['search_username']
Thats why it wont work. the text between ? and = in the js file should be what you look for in the filter_input in php file

**Pull request closed without merging**
